// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BatchFormat
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidBatchFormatPkgString = "ca45914b-4959-408a-98cf-87e4f9e97815";
        public static Guid guidBatchFormatPkg = new Guid(guidBatchFormatPkgString);

        public const string guidBatchFormatCmdSetString = "70fd9bbd-df20-4bc5-b51c-eaa35b408b7c";
        public static Guid guidBatchFormatCmdSet = new Guid(guidBatchFormatCmdSetString);

        public const string guidImagesString = "febad06e-3d16-493c-983c-c2f74073f0b2";
        public static Guid guidImages = new Guid(guidImagesString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SlnSubMemu = 0x0001;
        public const int ProjSubMemu = 0x0002;
        public const int SlnMenuGroup = 0x1010;
        public const int SlnSubMemuGroup = 0x1013;
        public const int ProjMenuGroup = 0x1011;
        public const int ProjSubMenuGroup = 0x1012;
        public const int cmdGroup = 0x1014;
        public const int cmdidRemoveUnusedUsings = 0x2001;
        public const int cmdidSortUsings = 0x2002;
        public const int cmdidRemoveAndSortUsings = 0x2003;
        public const int cmdidFormatDocument = 0x2004;
        public const int cmdidSortUsingsAndFormatDocument = 0x2005;
        public const int cmdidRemoveAndSortUsingsAndFormatDocument = 0x2006;
        public const int cmdidFormatDocument2 = 0x2007;
        public const int bmpRecommend = 0x0001;
        public const int bmpDelete = 0x0002;
        public const int bmpSort = 0x0003;
        public const int bmpDeleteSort = 0x0004;
        public const int bmpFormat = 0x0005;
        public const int bmpAll = 0x0006;
    }
}
